ProgrammersBlog.Mvc/Areas/Admin/Models/UserViewModel.cs
using ProgrammersBlog.Entities.Concrete;

namespace ProgrammersBlog.Mvc.Areas.Admin.Models
{
    public class UserViewModel
    {
        public User User { get; set; }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgrammersBlog.Entities.ComplexTypes;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Entities.Dtos.Classes;
using ProgrammersBlog.Entities.Dtos.Records;
using ProgrammersBlog.Mvc.Helpers.Abstract;
using ProgrammersBlog.Mvc.Helpers.Concrete;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Extensions;
using ProgrammersBlog.Shared.Utilities.Results.Abstract;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes.Concrete;
using System.Data;
using System.Text.Json;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class UserController : BaseController
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        #region Constractors
        public UserController( IImageHelper imageHelper, IServiceManager serviceManager):base(serviceManager, imageHelper)
        {
        }
        #endregion
        #region Methods
        public async Task<IActionResult> Index()
        {
            var users = await ServiceManager.AuthService.GetAllUsersInDataResultObjectAsync();
            return View(users.Data);
        }
        public async Task<IActionResult> AddUser()
        {
            HashSet<string> roles=new HashSet<string>  (await ServiceManager.AuthService.RoleManager.Roles.Select(r=>r.Name).ToListAsync());
            ViewBag.Roles = roles;
            return View(new UserAddDto() );
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser([FromForm] UserAddDto userAddDto)
        {
            HashSet<string> roles = new HashSet<string>(await ServiceManager.AuthService.RoleManager.Roles.Select(r => r.Name).ToListAsync());
            ViewBag.Roles = roles;
            if (ModelState.IsValid)
            {
                IDataResult<ImageUploadedDto> uploadedImageDataResult = await ImageHelper.UploadImage(userAddDto.UserName, userAddDto.PictureFile,PictureTypes.User);
                userAddDto.Picture = uploadedImageDataResult.ResultStatus == ResultStatus.Success ? uploadedImageDataResult.Data.FullName : "userImages/defaultUser.png";
                
                var result = await ServiceManager.AuthService.AddUserAsync(userAddDto);
                if (result.ResultStatus.Equals(ResultStatus.Success))
                { 
                    TempData["success"] = result.Message;
                    return RedirectToAction("Index");
                }
                else
                {
                    ImageHelper.Delete(userAddDto.Picture);
                    TempData["danger"] = result.Message;
                }
            }
            return View(userAddDto);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateUser([FromRoute] int id)
        {
            DataResult<UserDtoForGetOne> result =(DataResult < UserDtoForGetOne >)await ServiceManager.AuthService.GetUserInDataResultObjectAsync(id);
            return View(result.Data);
        }
        [HttpPost]
        public async Task<JsonResult> UpdateUser([FromForm]UserUpdateDto userUpdateDto)
        {
            if (!ModelState.IsValid)
            {
                Dictionary<string, string[]> errors = ModelState.ToDictionary(
                        kvp => kvp.Key,
                        kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                    );
                var ajaxErrorsResult = JsonSerializer.Serialize(errors);
                return Json(ajaxErrorsResult);
            }
            if (userUpdateDto.PictureFile is not null)
            {
                var deletedImageDtoResult = ImageHelper.Delete(userUpdateDto.Picture);
                if (deletedImageDtoResult.ResultStatus.Equals(ResultStatus.Success))
                {
                    var uploadedImageDataResult = await ImageHelper.UploadImage(userUpdateDto.UserName, userUpdateDto.PictureFile,PictureTypes.User);
                    userUpdateDto.Picture = uploadedImageDataResult.Data.FullName;
                }
                else
                {
                    return new JsonResult(new { success = false, message = deletedImageDtoResult.Message });
                }
            }
            var result = await ServiceManager.AuthService.UpdateUserAsync(userUpdateDto);
            var ajaxModelResult = JsonSerializer.Serialize(result);
            return Json(ajaxModelResult);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int userId)
        {
            User logInUser = await ServiceManager.AuthService.UserManager.GetUserAsync(HttpContext.User);
            var result = await ServiceManager.AuthService.HardDeleteUserAsync(userId,logInUser.Id);
            if (result.ResultStatus.Equals(ResultStatus.Success))
            {
                ImageHelper.Delete(result.Data);
            }
            var jsonResult= JsonSerializer.Serialize(result);
            return Json(jsonResult);
        }

        #endregion
    }
}

ProgrammersBlog.Mvc/Components/UsersCommentCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Services.Abstract;

namespace ProgrammersBlog.Mvc.Components
{
    public class UsersCommentCountViewComponent:ViewComponent
    {
        private readonly IServiceManager _serviceManager;
        public UsersCommentCountViewComponent(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }
        public async Task<string> InvokeAsync(string userName)
        {
            int result=await _serviceManager.CommentService.GetUserCommentCountAsync(userName);
            return result.ToString();

        }
    }
}

ProgrammersBlog.Mvc/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Entities.Concrete;
using System.Text.Json;
using ProgrammersBlog.Shared.Utilities.Results.Abstract;

namespace ProgrammersBlog.Mvc.Controllers
{
    public class UserController:Controller
    {
        private readonly IServiceManager _serviceManager;
        public UserController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromRoute]int id)
        {
            var user = await _serviceManager.AuthService.UserManager.GetUserAsync(HttpContext.User);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<JsonResult> EditSocialBlades([FromForm] SocialBlades socialBlades)
        {
            if (!ModelState.IsValid)
            {
                Dictionary<string, string[]> errors = ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                );
                var ajaxErrorsResult = JsonSerializer.Serialize(errors);
                return Json(ajaxErrorsResult);
            }
            else
            {
                Shared.Utilities.Results.Abstract.IResult result =await _serviceManager.AuthService.ChangeSocialBladesAsync(HttpContext.User, socialBlades);

                return Json(JsonSerializer.Serialize(result));
            }
        }
    }
}

ProgrammersBlog.Mvc/Views/User/Index.cshtml
@{
    Layout = "_UserLayout";
}
@using ProgrammersBlog.Shared.Entities.Concrete
@model User
<div class="container-sm mt-3">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-3">
                <div class="card-group">
                    <div class="card-body">
                        <center>
                            <img src="~/img/@Model.Picture" class="image-fluid center" style="max-width:10rem;max-height:20rem;" />
                        </center>
                        <div class="card-footer text-center lead">@Model.UserName</div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <table class="table lead">
                    <tr>
                        <td>
                            @Model.Email
                        </td>
                        <td id="email-Confirmed" data-id="@Model.EmailConfirmed">
                            @Html.Raw(Model.EmailConfirmed ? "<i class='fas fa-check text-success'></i>" : "<a class='btn btn-secondary rounded-4 btn-verify'style='width: 10rem'><i class='fas fa-times'></i> Doğrulanmadı</a>")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Model.PhoneNumber
                        </td>
                        <td id="phoneNumber-Confired" data-id="@Model.PhoneNumberConfirmed">
                            @Html.Raw(Model.EmailConfirmed ? "<i class='fas fa-check text-success'></i>" : "<a class='btn btn-secondary rounded-4 btn-verify' style='width: 10rem'><i class='fas fa-times'></i> Doğrulanmadı</a>")
                        </td>
                    </tr>
                    <tr>
                        <td >**********</td>
                        <td><a asp-controller="Account" asp-action="ChangePassword" class="btn btn-info rounded-4" style="width:10rem">Parolayı Güncelle</a></td>
                    </tr>
                    <tr>
                        <td>
                            <p>
                                Yorumlar
                                    @await Component.InvokeAsync("UsersCommentCount", new { userName = Model.UserName })
                            </p>

                        </td>
                        <td><div class="btn btn-dark rounded-4 get-more-users-comments" style="width:10rem"> Yorumlara Getir </div> </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <partial name="_ManageSocialBladesPartial" model="new SocialBlades{GitHubProfileUrl=Model.GitHubProfile,LinkedInProfileUrl=Model.LinkedInProfile}"></partial>

        </div>
     <br />
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-10">
                    <div class="table-responsive-lg">
                        <table class="table text-center  comments-table" style="display:none">
                            <thead>
                                <tr>
                                    <th scope="col" class="border-0">Yayınlanma Tarihi</th>
                                    <th scope="col" class="border-0">Yorum</th>
                                    <th scope="col" class="border-0">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody class="new-comment-area">
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<br />
@section Scripts{
    <script src="~/js/verifyAccount.js"></script>
    <script src="~/js/commentGetMoreUsersCommentButton.js"></script>
}

ProgrammersBlog.Mvc/Views/User/_ManageSocialBladesPartial.cshtml
@using ProgrammersBlog.Shared.Entities.Concrete
@model SocialBlades
<br />
<div class="container-sm p-3 rounded-4" style="background-color:#d9d9d9">
    <h5> Sosyal Medya</h5>
     <form method="post" id="form-social-blades">
        <div class="row mt-2">
            <div class="form-group">
                <label name="GitHubProfileUrl">
                    <i class="fab fa-github"></i>
                    Github
                </label>
                @if(Model.GitHubProfileUrl is null)
                {
                    <input name="GitHubProfileUrl" class="form-control" placeholder="Github Profil linki giriniz" />
                }
                else
                {
                    <input name="GitHubProfileUrl" class="form-control" value="@Model.GitHubProfileUrl" />
                }

                <span class="text-danger h6" asp-validation-for="@Model.GitHubProfileUrl"></span>
            </div>
        </div>
        <div class="row mt-2">
            <div class="form-group">
                <label name="LinkedInProfileUrl">
                    <i class="fab fa-linkedin-in"></i>
                    Linkedin
                </label>
                @if (Model.LinkedInProfileUrl is null)
                {
                    
                    <input name="LinkedInProfileUrl" class="form-control" placeholder="Linkedin Profil linki giriniz" />
                }
                else
                {
                    <input name="LinkedInProfileUrl" class="form-control" value="@Model.LinkedInProfileUrl" />

                }
            </div>
        </div>
        <div class="row mt-4">
            <center>
            <button style="width:10rem" class="btn btn-dark lead rounded-4 btn-change-social-blades">
                    <i class="fas fa-pencil-alt"></i>
                    Düzenle
            </button>
            </center>
        </div>
    </form>
</div>
<br/>
@section Scripts {
    <script src="~/js/changeSocialBlades.js"></script>
}
<script src="~/js/changeSocialBlades.js"></script>