ProgrammersBlog.Mvc/Areas/Admin/Components/SideBarNavViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Mvc.Areas.Admin.Models;

namespace ProgrammersBlog.Mvc.Areas.Admin.Components
{
    public class SideBarNavViewComponent:ViewComponent
    {
        private readonly UserManager<User> _userManager;
        public SideBarNavViewComponent(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            User user=await _userManager.GetUserAsync(HttpContext.User);
            IList<string> roles =(IList<string>)await _userManager.GetRolesAsync(user);
            return View(new UserWithRolesViewModel { Roles=roles,User=user});
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Components/TopBarNavViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Mvc.Areas.Admin.Models;

namespace ProgrammersBlog.Mvc.Areas.Admin.Components
{
    public class TopBarNavViewComponent:ViewComponent
    {
        UserManager<User> _userManager;
        public TopBarNavViewComponent(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            UserViewModel userViewModel = new UserViewModel();
            userViewModel.User = await _userManager.GetUserAsync(HttpContext.User);
            return View(userViewModel);
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Services.Abstract;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="admin")]
    public class RoleController : BaseController
    {
        public RoleController(IServiceManager serviceManager) : base(serviceManager)
        {
                
        }
        public async Task< IActionResult> Index()
        {
            IEnumerable<Role> roles = ServiceManager.AuthService.RoleManager.Roles.ToList();
            return View(roles);
        }
    }
}

ProgrammersBlog.Mvc/Components/TopNavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

using ProgrammersBlog.Services.Abstract;

namespace ProgrammersBlog.Mvc.Areas
{
    public class TopNavBarViewComponent:ViewComponent
    {
        IServiceManager _serviceManager;
        public TopNavBarViewComponent(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories=await _serviceManager.CategoryService.GetAllByIsDeletedAsync(false);
            return View(categories.Data);
        }
    }
}

ProgrammersBlog.Mvc/Components/UsersCommentCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Services.Abstract;

namespace ProgrammersBlog.Mvc.Components
{
    public class UsersCommentCountViewComponent:ViewComponent
    {
        private readonly IServiceManager _serviceManager;
        public UsersCommentCountViewComponent(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }
        public async Task<string> InvokeAsync(string userName)
        {
            int result=await _serviceManager.CommentService.GetUserCommentCountAsync(userName);
            return result.ToString();

        }
    }
}

ProgrammersBlog.Mvc/Controllers/ArticleController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.RequestParameters;
using ProgrammersBlog.Mvc.Models;
using ProgrammersBlog.Services.Abstract;
using System.Data.SqlTypes;

namespace ProgrammersBlog.Mvc.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IServiceManager _serviceManager;
        public ArticleController(IServiceManager serviceManager)
        {
            _serviceManager=serviceManager;
        }
        [HttpGet]
        public async Task<IActionResult> Index(ArticleRequestParameters requestParameters)
        {
            var articleDataResult=await _serviceManager.ArticleService.GetArticleSummariesByRequestParameters(requestParameters,true);
            Pagination pagination = new Pagination()
            {
                CurrentPage = requestParameters.PageNumber,
                ItemsPerPage = requestParameters.PageSize,
                TotalItems = await _serviceManager.ArticleService.GetAllSelectedMembersCountsync(requestParameters),
                SearchTerm = requestParameters.SearchTerm,
                CategoryId = requestParameters.CategoryId,
                OrderBy=requestParameters.OrderBy
            };
            return View(new ArticleListViewModel() { Articles=articleDataResult.Data,Pagination=pagination});
        }
        [HttpGet]
        public async Task<IActionResult> Get([FromRoute] int id)
        {
            var article=await _serviceManager.ArticleService.GetArticleWithUserAndCategoryAsync(id,true);
            return View(article.Data);
        }

    }
}

ProgrammersBlog.Mvc/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Dtos.Records;
using ProgrammersBlog.Entities.RequestParameters;
using ProgrammersBlog.Mvc.Models;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Extensions;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes.Concrete;
using System.Text.Json;

namespace ProgrammersBlog.Mvc.Controllers
{
    public class CommentController : Controller
    {
        private readonly IServiceManager _serviceManager;
        public CommentController(IServiceManager serviceManager)
        {
             _serviceManager=serviceManager;
        }
        [HttpPost]
        [Authorize]
        public async Task<JsonResult> Add([FromForm]CommentAddDto commentAddDto)
        {
            if (!ModelState.IsValid)
            {
                Dictionary<string, string[]> errors = ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                );
                var ajaxErrorsResult = JsonSerializer.Serialize(errors);
                return Json(ajaxErrorsResult);
            }
            commentAddDto.CreatedByName  = await _serviceManager.AuthService.GetUserNameAsync(HttpContext.User);
            var result= await _serviceManager.CommentService.AddAsync(commentAddDto);
            return Json(JsonSerializer.Serialize(result));
        }
        [HttpGet]
        public async Task<JsonResult> GetCommentsByResquestParameters(CommentRequestParameters commentRequestParameters)
        {
            var commentsDataResult=await _serviceManager.CommentService.GetCommentByRequestParametersAsync(commentRequestParameters,true);
            return Json(JsonSerializer.Serialize(commentsDataResult.Data));
        }
        [HttpGet]
        [Authorize]
        public async Task<JsonResult> GetUsersComments(CommentRequestParameters commentRequestParameters)
        {
            string userName = await _serviceManager.AuthService.GetUserNameAsync(HttpContext.User);
            var commentsDataResult = await _serviceManager.CommentService.GetCommentByUserNameAsync(userName, commentRequestParameters,true);
            return Json(JsonSerializer.Serialize(commentsDataResult.Data));

        }
    }
}

ProgrammersBlog.Mvc/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Entities.Concrete;
using System.Text.Json;
using ProgrammersBlog.Shared.Utilities.Results.Abstract;

namespace ProgrammersBlog.Mvc.Controllers
{
    public class UserController:Controller
    {
        private readonly IServiceManager _serviceManager;
        public UserController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromRoute]int id)
        {
            var user = await _serviceManager.AuthService.UserManager.GetUserAsync(HttpContext.User);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<JsonResult> EditSocialBlades([FromForm] SocialBlades socialBlades)
        {
            if (!ModelState.IsValid)
            {
                Dictionary<string, string[]> errors = ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                );
                var ajaxErrorsResult = JsonSerializer.Serialize(errors);
                return Json(ajaxErrorsResult);
            }
            else
            {
                Shared.Utilities.Results.Abstract.IResult result =await _serviceManager.AuthService.ChangeSocialBladesAsync(HttpContext.User, socialBlades);

                return Json(JsonSerializer.Serialize(result));
            }
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Views/Shared/Components/SideBarNav/default.cshtml
@model ProgrammersBlog.Mvc.Areas.Admin.Models.UserWithRolesViewModel
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark " id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Menü</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                    <div class="sb-nav-link-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-speedometer" viewBox="0 0 16 16">
                            <path d="M8 2a.5.5 0 0 1 .5.5V4a.5.5 0 0 1-1 0V2.5A.5.5 0 0 1 8 2zM3.732 3.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 8a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 8zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 7.31A.91.91 0 1 0 8.85 8.569l3.434-4.297a.389.389 0 0 0-.029-.518z" />
                            <path fill-rule="evenodd" d="M6.664 15.889A8 8 0 1 1 9.336.11a8 8 0 0 1-2.672 15.78zm-4.665-4.283A11.945 11.945 0 0 1 8 10c2.186 0 4.236.585 6.001 1.606a7 7 0 1 0-12.002 0z" />
                        </svg>
                    </div>
                    Dashboard
                </a>
                 <div class="sb-sidenav-menu-heading">İçerikler</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
                    Kategoriler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Article" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-newspaper"></i></div>
                    Makaleler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">
                    <div class="sb-nav-link-icon">
                        <i class="fas fa-comments"></i>
                    </div>
                    Yorumlar
                </a>
                @if (Model.Roles.Any(r=>r.Equals("admin")))
                {
                    <div class="sb-sidenav-menu-heading">Kullanıcılar</div>
                    <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">
                        <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                        Kullanıcılar
                    </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Role" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-sitemap"></i></div>
                    Roller
                </a>
                }
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Giriş yapan kullanıcı : </div>
            @Model.User.UserName
        </div>
    </nav>
</div>