ProgrammersBlog.Mvc/Areas/Admin/Models/UserViewModel.cs
using ProgrammersBlog.Entities.Concrete;

namespace ProgrammersBlog.Mvc.Areas.Admin.Models
{
    public class UserViewModel
    {
        public User User { get; set; }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Controllers/DashboardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Data.Abstract;
using ProgrammersBlog.Data.Concrete;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Services.Concrete;

namespace ProgrammersBlog.Mvc.Areas.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        IDataCountService _categoryCountManager;
        IDataCountService _articleCountManager;
        IDataCountService _commentCountManager;


        public DashboardController(ICategoryService categoryManager,IArticleService articleManager, ICommentService commentCountManager)
        {
            _categoryCountManager = (IDataCountService)categoryManager;
            _articleCountManager = (IDataCountService)articleManager;
            _commentCountManager = (IDataCountService)commentCountManager;
        }
        [Authorize(Roles = "admin,editor")]
        public async Task<IActionResult> Index()
        {
            int activeCategoryCount = await (_categoryCountManager.GetActiveDataCountAsync());
            int deletedCategoryCount=await _categoryCountManager.GetDeletedDataCountAsync();
            int categoryCount=await _categoryCountManager.CountAsync();

            int deletedArticleCount = await _articleCountManager.GetDeletedDataCountAsync();
            int activeArticleCount = await _articleCountManager.GetActiveDataCountAsync();
            int articleCount=await _articleCountManager.CountAsync();

            int deletedCommentCount = await _commentCountManager.GetDeletedDataCountAsync();
            int activeCommentCount = await _commentCountManager.GetActiveDataCountAsync();
            int commentCount = await _commentCountManager.CountAsync();

            var dashboardViewModel = new DashboardViewModel()
            {
                ActiveCategoryCount = activeCategoryCount,
                CategoryCount = categoryCount,
                DeletedCategoryCount = deletedCategoryCount,

                ActiveArticleCount= activeArticleCount,
                DeletedArticleCount = deletedArticleCount,
                ArticleCount=articleCount,

                ActiveCommentCount=activeCommentCount,
                DeletedCommentCount=deletedCommentCount,
                CommentCount=commentCount
            };
            return View(dashboardViewModel);
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgrammersBlog.Entities.ComplexTypes;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Entities.Dtos.Classes;
using ProgrammersBlog.Entities.Dtos.Records;
using ProgrammersBlog.Mvc.Helpers.Abstract;
using ProgrammersBlog.Mvc.Helpers.Concrete;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Extensions;
using ProgrammersBlog.Shared.Utilities.Results.Abstract;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes.Concrete;
using System.Data;
using System.Text.Json;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class UserController : BaseController
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        #region Constractors
        public UserController( IImageHelper imageHelper, IServiceManager serviceManager):base(serviceManager, imageHelper)
        {
        }
        #endregion
        #region Methods
        public async Task<IActionResult> Index()
        {
            var users = await ServiceManager.AuthService.GetAllUsersInDataResultObjectAsync();
            return View(users.Data);
        }
        public async Task<IActionResult> AddUser()
        {
            HashSet<string> roles=new HashSet<string>  (await ServiceManager.AuthService.RoleManager.Roles.Select(r=>r.Name).ToListAsync());
            ViewBag.Roles = roles;
            return View(new UserAddDto() );
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUser([FromForm] UserAddDto userAddDto)
        {
            HashSet<string> roles = new HashSet<string>(await ServiceManager.AuthService.RoleManager.Roles.Select(r => r.Name).ToListAsync());
            ViewBag.Roles = roles;
            if (ModelState.IsValid)
            {
                IDataResult<ImageUploadedDto> uploadedImageDataResult = await ImageHelper.UploadImage(userAddDto.UserName, userAddDto.PictureFile,PictureTypes.User);
                userAddDto.Picture = uploadedImageDataResult.ResultStatus == ResultStatus.Success ? uploadedImageDataResult.Data.FullName : "userImages/defaultUser.png";
                
                var result = await ServiceManager.AuthService.AddUserAsync(userAddDto);
                if (result.ResultStatus.Equals(ResultStatus.Success))
                { 
                    TempData["success"] = result.Message;
                    return RedirectToAction("Index");
                }
                else
                {
                    ImageHelper.Delete(userAddDto.Picture);
                    TempData["danger"] = result.Message;
                }
            }
            return View(userAddDto);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateUser([FromRoute] int id)
        {
            DataResult<UserDtoForGetOne> result =(DataResult < UserDtoForGetOne >)await ServiceManager.AuthService.GetUserInDataResultObjectAsync(id);
            return View(result.Data);
        }
        [HttpPost]
        public async Task<JsonResult> UpdateUser([FromForm]UserUpdateDto userUpdateDto)
        {
            if (!ModelState.IsValid)
            {
                Dictionary<string, string[]> errors = ModelState.ToDictionary(
                        kvp => kvp.Key,
                        kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                    );
                var ajaxErrorsResult = JsonSerializer.Serialize(errors);
                return Json(ajaxErrorsResult);
            }
            if (userUpdateDto.PictureFile is not null)
            {
                var deletedImageDtoResult = ImageHelper.Delete(userUpdateDto.Picture);
                if (deletedImageDtoResult.ResultStatus.Equals(ResultStatus.Success))
                {
                    var uploadedImageDataResult = await ImageHelper.UploadImage(userUpdateDto.UserName, userUpdateDto.PictureFile,PictureTypes.User);
                    userUpdateDto.Picture = uploadedImageDataResult.Data.FullName;
                }
                else
                {
                    return new JsonResult(new { success = false, message = deletedImageDtoResult.Message });
                }
            }
            var result = await ServiceManager.AuthService.UpdateUserAsync(userUpdateDto);
            var ajaxModelResult = JsonSerializer.Serialize(result);
            return Json(ajaxModelResult);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int userId)
        {
            User logInUser = await ServiceManager.AuthService.UserManager.GetUserAsync(HttpContext.User);
            var result = await ServiceManager.AuthService.HardDeleteUserAsync(userId,logInUser.Id);
            if (result.ResultStatus.Equals(ResultStatus.Success))
            {
                ImageHelper.Delete(result.Data);
            }
            var jsonResult= JsonSerializer.Serialize(result);
            return Json(jsonResult);
        }

        #endregion
    }
}

ProgrammersBlog.Mvc/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Entities.Concrete;
using System.Text.Json;
using ProgrammersBlog.Shared.Utilities.Results.Abstract;

namespace ProgrammersBlog.Mvc.Controllers
{
    public class UserController:Controller
    {
        private readonly IServiceManager _serviceManager;
        public UserController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromRoute]int id)
        {
            var user = await _serviceManager.AuthService.UserManager.GetUserAsync(HttpContext.User);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<JsonResult> EditSocialBlades([FromForm] SocialBlades socialBlades)
        {
            if (!ModelState.IsValid)
            {
                Dictionary<string, string[]> errors = ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                );
                var ajaxErrorsResult = JsonSerializer.Serialize(errors);
                return Json(ajaxErrorsResult);
            }
            else
            {
                Shared.Utilities.Results.Abstract.IResult result =await _serviceManager.AuthService.ChangeSocialBladesAsync(HttpContext.User, socialBlades);

                return Json(JsonSerializer.Serialize(result));
            }
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Views/User/AddUser.cshtml
@model UserAddDto
<br />
    <ol class="breadcrumb mb-3 mt-1">
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a></li>
        <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="User" asp-action="Index">Kullanıcılar</a></li>
        <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="User" asp-action="AddUser">Kullanıcı ekle</a></li>
    </ol>
<div class="row  ">
    <div class="col-md-12">
        <div class="col-md-5" style="margin:auto;">
        <div class="lead">
            <h4 class="modal-title"><i class="fas fa-plus"></i>Kullanıcı ekle</h4>
            <br />
                <form method="post" asp-area="Admin" asp-controller="User" asp-action="AddUser" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="@Model.UserName"></label>
                        <input class="form-control" asp-for="@Model.UserName" />
                        <span asp-validation-for="@Model.UserName" class="text-danger" style="font-size=14px;"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Email"></label>
                        <input  class="form-control" asp-for="@Model.Email" />
                        <span asp-validation-for="@Model.Email" class="text-danger" style="font-size=14px;"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Password"></label>
                        <input  asp-for="@Model.Password" class="form-control" />
                        <span asp-validation-for="@Model.Password" class="text-danger" style="font-size=14px;"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.PhoneNumber"></label>
                        <input  asp-for="@Model.PhoneNumber" class="form-control" value="+905" />
                        <span asp-validation-for="@Model.PhoneNumber" class="text-danger" style="font-size=14px;"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.PictureFile"></label>
                        <input accept="image/*" class="form-control-file" asp-for="@Model.PictureFile" />
                        <span asp-validation-for="@Model.PictureFile" class="text-danger" style="font-size=14px;"></span>

                    </div>
                    <div class="col-md-6">
                        <div class="lead p-2 mt-2">
                            @foreach (var item in ViewBag.Roles)
                            {
                                <div class="form-check">
                                    <input type="checkbox" name="Roles" value="@item" class="form-check-input border border-dark" />
                                    <label class="form-check-label">@item</label>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="text-danger lead error-messages" style="font-size:14px;"></div>
                    <br />
                    <div class="modal-footer ">
                        <div class="btn-group text-white" style="margin:auto">
                            <a asp-area="Admin" asp-controller="User" asp-action="Index" class="btn btn-danger rounded-0">
                                <i class="fas fa-times"></i>
                                İptal
                            </a>
                            <button class="btn text-white rounded-0 btn-primary" type="submit">
                                <i class="fas fa-save"></i>
                                Kaydet
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

ProgrammersBlog.Mvc/Areas/Admin/Views/User/Index.cshtml
@model UsersListDto
@{
    Layout = "_Layout";
     
}
<title>Kullanıcılar</title>
@if (Model.ResultStatus == ResultStatus.Success)
{
    <div class="row ml-3">
        <ol class="breadcrumb mb-3 mt-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="User" asp-action="Index">Kullanıcılar</a></li>
        </ol>
    </div>
    <div id="moddelPlaceHolder" aria-hidden="true"></div>
    <div class="card mb-4 mt-2">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Kullanıcılar
        </div>
        <div class="row">
            <div class="container text-center">
                <div class="btn-group mt-3">
                    <a class="btn btn-sm btn-success rounded-0" asp-area="Admin" asp-controller="User" asp-action="AddUser" id="btnAdd">
                        <i class="fas fa-plus"></i>
                        Kullanıcı Ekle
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <button id="btnLoading" class="btn btn-lg mt-1" style="display:none;width:60px;height:60px;">
                <i class="fas fa-spinner fa-pulse text-primary"></i>
            </button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="usersTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Kullanıcı Adı</th>
                            <th>Email</th>
                            <th>Telefon Numarası</th>
                            <th>Kullanıcı fotoğrafı</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Kullanıcı Adı</th>
                            <th>Email</th>
                            <th>Telefon Numarası</th>
                            <th>Kullanıcı fotoğrafı</th>
                            <th>İşlemler</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var user in Model.Users)
                        {
                            <tr name="@user.Id ">
                                <td>@user.Id</td>
                                <td>@user.UserName</td>
                                <td>@user.Email</td>
                                <td>@user.PhoneNumber</td>
                                <td>
                                    <img src="~/img/@user.Picture" style="max-width:100px;max-height:200px;">
                                </td>
                                <td>
                                    <div class="">
                                        <button class="btn-remove btn-sm btn-block btn-danger rounded-0 border-0" data-id="@user.Id">
                                            <i class="fas fa-trash-alt"></i>
                                            Sil
                                        </button>
                                        <a asp-area="Admin" asp-controller="User" asp-action="UpdateUser" asp-route-id="@user.Id" class="btn btn-sm btn-block btn-warning mt-1 rounded-0 btn-edit">
                                            <i class="fas fa-edit"></i>
                                            Düzenle
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
@if (Model.ResultStatus.Equals(ResultStatus.Error))
{
    <h1 class="lead text-danger">@Model.Message</h1>
    <br />
    <h6>Admin alanına dönmek için <a class="alert-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">tıklayınız.</a></h6>
}
@section Scripts
    {
    <script src="~/AdminLTE/js/userDelete.js"></script>
    <script src="~/AdminLTE/js/userIndex.js">
    </script>
}

ProgrammersBlog.Mvc/Areas/Admin/Views/User/UpdateUser.cshtml
@model ProgrammersBlog.Entities.Dtos.Classes.UserDtoForGetOne
@if (Model.ResultStatus.Equals(ResultStatus.Error))
{
    <h3 class="text-danger">
        @Model.Message
    </h3>
    <br />
    <a asp-controller="User" asp-action="Index"> Kulanıcı sayfasına dönün.
    </a>
}
else
{
    <br />
    <div class="row ml-3">
        <ol class="breadcrumb mb-3 mt-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="User" asp-action="Index">Kullanıcılar</a></li>
            <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="User" asp-action="UpdateUser">Kullanıcı düzenle</a></li>
        </ol>
    </div>
    <div class="row  p-2">
        <div class=" p-4 bg-light-2" style="width:380px;margin:auto;">
            <div class="lead">
                <h4 class="modal-title"><i class="fas fa-edit"></i>Kullanıcı Düzenle</h4>
                <br />
                <div class="">
                    <form method="post" asp-area="Admin" id="form-user-update">
                        <div class="text-center" >
                            <img src="~/img/@Model.User.Picture" style="max-width:100px;max-height:200px;" />
                        </div>
                        <input type="hidden" name="Picture" value="@Model.User.Picture" />
                        <input type="hidden" name="Id" value="@Model.User.Id" />
                        <input type="hidden" name="PasswordHash" value="@Model.User.PasswordHash" />
                        <div class="form-group">
                            <label >Kullanıcı Adı</label>
                            <input id="modelName" class="form-control" name="UserName" value="@Model.User.UserName" />
                        </div>
                        <div class="form-group">
                            <label name="Email">E-Mail</label>
                            <input id="modelEmail" class="form-control" name="Email" value="@Model.User.Email" />
                        </div>
                        <div class="form-group">
                            <label name="PhoneNumber">Telefon Numarası</label>
                            <input id="modelPhoneNumber" name="PhoneNumber" class="form-control" value="@Model.User.PhoneNumber" />
                        </div>
                        <div class="form-group">
                            <label>Yeni profil fotoğrafını seç</label>
                            <input id="modelPicture" name="PictureFile" type="file" accept="image/*" class="form-control-file" />
                        </div>
                        <div class="col-md-6">
                            <div class="lead p-2 mt-2">
                                Yetkiler:
                                @foreach (var item in Model.Roles)
                                {
                                    <div class="form-check">
                                        <input type="checkbox" name="Roles" value="@item" checked="@Model.UserRoles.Contains(item)" class="form-check-input" style="border:1px solid black;" />
                                        <label class="form-check-label">@item</label>
                                    </div>
                                }
                            </div>
                            <div class="text-danger" asp-validation-summary="All">
                            </div>
                        </div>
                        <div class="text-danger lead error-messages" style="font-size:14px;"></div>
                        <br />
                        <div class="modal-footer ">
                            <div class="btn-group text-white" style="margin:auto">
                                <a asp-area="Admin" asp-controller="User" asp-action="Index" class="btn btn-danger rounded-0">
                                    <i class="fas fa-times"></i>
                                    İptal
                                </a>
                                <button class="btn text-white rounded-0 btn-primary btn-save ">
                                    <i class="fas fa-save"></i>
                                    Kaydet
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
}
@section Scripts {
    <script src="~/AdminLTE/js/userUpdate.js">
    </script>
}