ProgrammersBlog.Mvc/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Results.ComplexTypes;
using ProgrammersBlog.Entities.Dtos.Records;
using Microsoft.AspNetCore.Authorization;
using ProgrammersBlog.Mvc.Helpers.Concrete;
using Microsoft.AspNetCore.Identity;
using ProgrammersBlog.Entities.Concrete;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : BaseController
    {
        #region Constractor
        public CategoryController(IServiceManager serviceManager):base(serviceManager)
        {
        }
        #endregion

        #region Methods
        [Authorize(Roles = "admin,editor")]
        public async Task<IActionResult> Index()
        {
            var result =await ServiceManager.CategoryService.GetAllAsync();
            
            return View(result.Data);
        }
        [Authorize(Roles = "admin,editor")]
        public IActionResult AddCategory()
        {
            return View();
        }
        [Authorize(Roles = "admin,editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCategory([FromForm]CategoryAddDto categoryAddDto)
        {
            if (ModelState.IsValid)
            {
                var user = await ServiceManager.AuthService.UserManager.GetUserAsync(HttpContext.User);
                var result = await ServiceManager.CategoryService.AddAsync(categoryAddDto, user.UserName);
                if (result.ResultStatus.Equals(ResultStatus.Success))
                {
                    TempData["success"] = result.Message;
                    return Redirect("Index");
                }
                else if (result.ResultStatus.Equals(ResultStatus.Error))
                {
                    TempData["danger"] = result.Message;

                }
            }
            return View(categoryAddDto);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<JsonResult> Delete(int categoryId)
        {
            var result = await ServiceManager.CategoryService.DeleteAsync(categoryId, "Batuhan Doğan");
            var ajaxResult=JsonSerializer.Serialize(result);
            return Json(ajaxResult);
        }
        [Authorize(Roles = "admin,editor")]
        [HttpGet]
        public async Task<IActionResult> UpdateCategory([FromRoute] int id)
        {
            var category = await ServiceManager.CategoryService.GetAsync(id);
            if (category.ResultStatus.Equals(ResultStatus.Success))
            {
                return View(category.Data);
            }
            return View(category.Data);
        }
        [Authorize(Roles = "admin,editor")]
        [HttpPost]
        public async Task<JsonResult> UpdateCategory([FromForm] CategoryUpdateDto categoryUpdateDto)
        {
            if (ModelState.IsValid)
            {
                var user =await ServiceManager.AuthService.UserManager.GetUserAsync(HttpContext.User);
                var result = await ServiceManager.CategoryService.UpdateAsync(categoryUpdateDto, user.UserName);
                var ajaxModelResult = JsonSerializer.Serialize(result.Data);
                return Json(ajaxModelResult);
            }
            Dictionary<string, string[]> errors = ModelState.ToDictionary(
                kvp => kvp.Key,
                kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
            );
            var ajaxErrorsResult = JsonSerializer.Serialize(errors);
            return Json(ajaxErrorsResult);
        }
        #endregion
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Controllers/DashboardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Data.Abstract;
using ProgrammersBlog.Data.Concrete;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Services.Concrete;

namespace ProgrammersBlog.Mvc.Areas.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        IDataCountService _categoryCountManager;
        IDataCountService _articleCountManager;
        IDataCountService _commentCountManager;


        public DashboardController(ICategoryService categoryManager,IArticleService articleManager, ICommentService commentCountManager)
        {
            _categoryCountManager = (IDataCountService)categoryManager;
            _articleCountManager = (IDataCountService)articleManager;
            _commentCountManager = (IDataCountService)commentCountManager;
        }
        [Authorize(Roles = "admin,editor")]
        public async Task<IActionResult> Index()
        {
            int activeCategoryCount = await (_categoryCountManager.GetActiveDataCountAsync());
            int deletedCategoryCount=await _categoryCountManager.GetDeletedDataCountAsync();
            int categoryCount=await _categoryCountManager.CountAsync();

            int deletedArticleCount = await _articleCountManager.GetDeletedDataCountAsync();
            int activeArticleCount = await _articleCountManager.GetActiveDataCountAsync();
            int articleCount=await _articleCountManager.CountAsync();

            int deletedCommentCount = await _commentCountManager.GetDeletedDataCountAsync();
            int activeCommentCount = await _commentCountManager.GetActiveDataCountAsync();
            int commentCount = await _commentCountManager.CountAsync();

            var dashboardViewModel = new DashboardViewModel()
            {
                ActiveCategoryCount = activeCategoryCount,
                CategoryCount = categoryCount,
                DeletedCategoryCount = deletedCategoryCount,

                ActiveArticleCount= activeArticleCount,
                DeletedArticleCount = deletedArticleCount,
                ArticleCount=articleCount,

                ActiveCommentCount=activeCommentCount,
                DeletedCommentCount=deletedCommentCount,
                CommentCount=commentCount
            };
            return View(dashboardViewModel);
        }
    }
}

ProgrammersBlog.Mvc/Areas/Admin/Views/Category/AddCategory.cshtml
@model CategoryAddDto
<div class="row">
    <ol class="breadcrumb mb-3 mt-2">
        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a></li>
        <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Category" asp-action="Index">Kategori</a></li>
        <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Category" asp-action="AddCategory">Kategori ekle</a></li>
    </ol>
</div>
    <div class="row p-2  ">
        <div class="col-md-12">
            <div class="col-md-5" style="margin:auto">
                <div class=" p-4  " >
                    <div class="lead">
                        <h4 class="modal-title" ><i class="fas fa-plus"></i> Kategori Ekle</h4>
                        <br />
                        <div>
                        <form method="post" asp-area="Admin" asp-controller="Category" asp-action="AddCategory" enctype="multipart/form-data">
                                <div class="form-group">
                                    <label asp-for="@Model.Name"></label>
                                    <input  class="form-control" asp-for="@Model.Name" />
                                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="@Model.Description"></label>
                                    <input  class="form-control" asp-for="@Model.Description" />
                                </div>
                                <div class="form-group">
                                    <label asp-for="@Model.Note"></label>
                                    <input  class="form-control " asp-for="@Model.Note" />
                                </div>
                            <div class="form-group form-check">
                                <input type="checkbox" class="form-check-input border border-dark" asp-for="@Model.IsActive" />
                                    <label asp-for="@Model.IsActive" class="form-check-label"></label>
                                </div>
                                <br />
                                <div class="modal-footer">
                                    <div class="btn-group text-white text-center">
                                        <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="btn btn-danger ">
                                            <i class="fas fa-times"></i>
                                            İptal
                                        </a>
                                        <button type="submit" class="btn text-white btn-primary " >
                                            <i class="fas fa-save"></i>
                                            Kaydet
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
            </div>
        </div>
    </div>

ProgrammersBlog.Mvc/Areas/Admin/Views/Category/Index.cshtml
@model CategoryListDto
@{
    Layout = "_Layout";
    ViewData["Title"] = " Kategoriler Index";
}
@if (Model.ResultStatus == ResultStatus.Success)
{
    <div class="row ml-3">
        <ol class="breadcrumb mb-3 mt-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Category" asp-action="Index">Kategoriler</a></li>
        </ol>
    </div>
<div id="moddelPlaceHolder" aria-hidden="true"></div>
<div class="card mb-4 mt-2">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Kategoriler
    </div>
    <div class="row">
        <div class=" text-center">
            <div class="btn-group mt-3">
                    <a class="btn btn-sm btn-success rounded-0" asp-area="Admin" asp-controller="Category" asp-action="AddCategory" id="btnAdd">
                    <i class="fas fa-plus"></i>
                    Kategori Ekle
                </a>
                    <button class="btn btn-sm btn-info text-white" id="reload">
                    <i class="fas fa-redo-alt"></i>
                    Sayfayı Yenile
                </button>
                <br>
            </div>
        </div>                       
    </div>
    <div class="row">
            <button id="btnLoading" class="btn btn-lg mt-1" style="display:none;width:60px;height:60px;">
                <i class="fas fa-spinner fa-pulse text-primary"></i>
            </button>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="categoriesTable" width="100%" cellspacing="0">
                <thead>
                    <tr >
                        <th>ID</th>
                        <th>Adı</th>
                        <th>Açıklaması</th>
                        <th>Aktif Mi?</th>
                        <th>Silinmiş Mi?</th>
                        <th>Not</th>
                        <th>Oluşturulma Tarihi</th>
                        <th>Oluşturan Kullanıcı Adı</th>
                        <th>Son Düzenlenme Tarihi</th>
                        <th>Son Düzenleyen Kullanıcı Adı</th>
                        <th>İşlemler</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Adı</th>
                        <th>Açıklaması</th>
                        <th>Aktif Mi?</th>
                        <th>Silinmiş Mi?</th>
                        <th>Not</th>
                        <th>Oluşturulma Tarihi</th>
                        <th>Oluşturan Kullanıcı Adı</th>
                        <th>Son Düzenlenme Tarihi</th>
                        <th>Son Düzenleyen Kullanıcı Adı</th>
                        <th>İşlemler</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var category in Model.Categories)
                    {
                        <tr name="@category.Id ">
                            <td>@category.Id</td>
                            <td>@category.Name</td>
                            <td>@category.Description</td>
                            <td>
                                @{string isActive=(category.IsActive==true)?"Evet":"Hayır";
                                }@isActive
                                </td>
                            <td>
                                @{
                                    string isDeleted = (category.IsDeleted == true) ? "Evet" : "Hayır";
                                }
                                @isDeleted
                            </td>
                            <td>@category.Note</td>
                            <td>@category.CreatedTime.ToShortDateString()</td>
                            <td>@category.CreatedByName</td>
                            <td>@category.ModifiedTime.ToShortDateString()</td>
                            <td>@category.ModifiedByName</td>
                            <td>
                                <div class="text-center">
                                        <button class="btn btn-block btn-sm btn-delete btn-danger rounded-0" data-id="@category.Id">
                                        <i class="fas fa-trash-alt"></i>
                                        Sil
                                    </button>
                                        <a class="btn btn-sm btn-block btn-warning mt-1 rounded-0 btn-edit" asp-area="Admin" asp-controller="Category" asp-action="UpdateCategory" asp-route-id="@category.Id">
                                            <i class="far fa-edit"></i>
                                            Düzenle
                                    </a>
                                </div>
                        
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

}
@if (Model.ResultStatus.Equals(ResultStatus.Error))
{
    <h1 class="lead text-danger">@Model.Message</h1>
    <br />
    <h6>Admin alanına dönmek için <a class="alert-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">tıklayınız.</a></h6>
}
@section Scripts
{
    <script src="~/AdminLTE/js/categoryIndex.js">
    </script>
}

ProgrammersBlog.Mvc/Areas/Admin/Views/Category/UpdateCategory.cshtml
@model CategoryDtoForGetOne
@if (Model.ResultStatus.Equals(ResultStatus.Success))
{
    <div class="row ml-3">
        <ol class="breadcrumb mb-3 mt-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Category" asp-action="Index">Kategoriler</a></li>
            <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Category" asp-action="UpdateCategory">Kategori Düzenle</a></li>
        </ol>
    </div>
    <div class="row p-2">
        <div class="bg-light p-4" style="width:380px;margin:auto;">
            <div class="lead">
                <h4 class="modal-title"><i class="fas fa-edit"></i> Kategori Düzenle</h4>
                <br />
                <div class="">
                    <form method="post" asp-area="Admin" id="form-category-update">
                        <div asp-validation-summary="All" class="text-danger"  aria-hidden="true" style="display:none"></div>
                        <div class="form-group">
                            <label> Kategori Adı</label>
                            <input  value="@Model.Category.Name" name="Name" class="form-control " />
                        </div>
                        <div class="form-group">
                            <label>Kategori Açıklaması</label>
                            <input name="Description" value="@Model.Category.Description" class="form-control" />
                        </div>
                        <input type="hidden" value="@Model.Category.Id" name="Id" />
                        <div class="form-group">
                            <label>Not</label>
                            <input  name="Note" value="@Model.Category.Note" class="form-control" />
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="IsActive" style="border:1px solid black;" class="form-check-input" @(Model.Category.IsActive ? "checked" : "") />
                            <label class="form-check-label">Aktif mi?</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" style="border:1px solid black;" name="IsDeleted" @(Model.Category.IsDeleted ? "checked" : "") />
                            <label>Silinmiş mi?</label>
                        </div>
                        <div class="text-danger lead error-messages" style="font-size:14px;"></div>
                        <div class="modal-footer">
                            <div class="btn-group text-white text-center">
                                <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="btn btn-danger">
                                    <i class="fas fa-times"></i>
                                    İptal
                                </a>
                                <button class="btn text-white  btn-primary btn-save ">
                                    <i class="fas fa-save"></i>
                                    Kaydet
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}
@if (Model.ResultStatus.Equals(ResultStatus.Error))
{
    <h1 class="lead text-danger">@Model.Message</h1>
    <br />
    <h6>Admin alanına dönmek için <a class="alert-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">tıklayınız.</a></h6>
}
@section Scripts
{
    <script src="~/AdminLTE/js/categoryUpdate.js">
    </script>
}